#!/bin/bash

cat /opt/shibboleth-idp/logs/idp-process.log |
tr '\n' ' ' |
sed 's/"urn:oasis:names:tc:SAML:2.0:assertion"/\nrelevant.field.assertion.id:/g'|
sed 's/saml2:Attribute FriendlyName=\"uid\"/\"\nrelevant.field.uid:/g'|
sed s/'FriendlyName="sarl_url"'/'\nrelevant.field.assertion.sarlurl:/g' |
grep relevant.field|
cut -c-260 |
grep -B1 -A1 relevant.field.uid |
sed 's/xs:string\">/\nrelevant.field.assertion.values:\"/g' |
grep relevant.field.assertion |
sed 's/\/saml2/\"g/g'|
cut -d\" -f-2 |
tr '<' '"'|
tr '\n' ' '|
sed 's/ relevant.field.assertion.values/\" relevant.field.assertion.values/g'|
sed 's/relevant.field.assertion.id/\nrelevant.field.id/g'|
cut -d\" -f2,4,8|
sed s/\"/' '/g|
awk '{print $2":"$1":"$3}' |
grep -v "::" > saml_attr_script_file_v2

